fix(libs/movex-core-util): Fixed linting error in core-types.ts
movesthatmatter/movex pull request #144
Opened 2023-10-14 21:06 UTC by Abhishek-Mallick

Status:
Closes: https://github.com/movesthatmatter/movex/issues/126

Fixed linting issues in `core-types.ts` in `libs-movex-core-util`

2023-10-14 21:17 UTC, GabrielCTroia requested changes
Just one suggestions

2023-10-14 21:17 UTC, GabrielCTroia commented on libs/movex-core-util/src/lib/core-types.ts
> +export type MovexClient<Info extends UnknownRecord = Record<string, never>> = {
Hey @Abhishek-Mallick, thank you for these changes. As you're already using `Record<string, never>` in 2 places here, and weit could most likely be used in other places as well, I suggest to create a new type `EmptyObject = Record<string, never>` and use that everywhere is needed!

2023-10-15 21:31 UTC, Abhishek-Mallick commented
Was having issues commiting over the previous PR for which created a new PR: https://github.com/movesthatmatter/movex/pull/144 with all the mentioned changes

2023-10-20 18:55 UTC, GabrielCTroia commented
> Was having issues commiting over the previous PR for which created a new PR: #152 with all the mentioned changes

Ok, I'm going to close this PR then!

2023-10-20 18:55 UTC, closed without merging