refactor: removal of `initMovexWithLocalMaster` function and related unused dependencies
movesthatmatter/movex pull request #65
Opened 2023-10-09 17:16 UTC by Abhishek-Mallick

Status:
Closes: https://github.com/movesthatmatter/movex/issues/59
- [x] Have safely removed `initMovexWithLocalMaster` function
- [x] Unused imports removed

2023-10-09 19:26 UTC, GabrielCTroia requested changes
Just two small changes and it's good to go! Thank you

2023-10-09 19:26 UTC, GabrielCTroia commented on libs/movex/package-lock.json
> +{
This file got generated when you ran 'npm install' I believe. We use `yarn` for the whole project so we don't need this, as it'll create conflicts. Could you please remove it? 🙏

2023-10-09 19:26 UTC, GabrielCTroia commented on libs/movex/src/lib/client/init.ts
> -
You can safely remove the comments above as well, starting with line 54. 🙏

2023-10-09 21:00 UTC, Abhishek-Mallick commented
Should now be good commit: f6dae88b589b4adb441cfe71f1afb783819a7b8e

2023-10-09 21:08 UTC, GabrielCTroia approved these changes

2023-10-09 21:09 UTC, GabrielCTroia commented
One last thing:

Your first 2 commits are unsigned and I can't merge, could you please sign them as well! See this https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification or use this directly `git rebase --exec 'git commit --amend --no-edit -n -S' -i YOUR_BRANCH`

2023-10-09 21:11 UTC, GabrielCTroia commented
After this your PR will be merged to main! 🙏🚀

2023-10-09 22:10 UTC, Abhishek-Mallick commented
I having difficulties verifying the first two commits
The command dosent change anything
Please look through this @GabrielCTroia

2023-10-11 17:29 UTC, merged

2023-10-11 17:30 UTC, GabrielCTroia commented
Hey @Abhishek-Mallick , just merged it! Sorry for the struggle and thank you so much for you effort!

One last thing, could you please star the repo so we can bump it up today for #hacktoberfest!? ❤️🚀🙏

And also, do you have any feedback for the project? 
- did you find it easy to navigate or to understand the docs